name: Build example project
on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

  
jobs:
  format_projects:
    name: "Build - ${{ matrix.name }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"
        
    - name: Set up Go 1.15.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
      id: go

    - name: Setup Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/bzlmod_cache/*.sha256
        key: ${{ runner.os }}-${{ hashFiles('**/generate/**') }}
        restore-keys: |
          ${{ runner.os }}-
          ${{ runner.os }}

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.8'

    - name: Install Buildifier
      run: |
        cd $(mktemp -d)
        GO111MODULE=on go get github.com/bazelbuild/buildtools/buildifier@latest

    - run: ./generate_subprojects.sh
      working-directory: monorepo_tools

    - name: Check Output
      run:  git --no-pager diff --exit-code HEAD --submodule=diff

    - name: Generate diff
      run: git diff HEAD --submodule=diff > generation-fixes.patch
      if: ${{ failure() }}

    - uses: actions/upload-artifact@v2
      with:
        name: generation fixes
        path: generation-fixes.patch
      if: ${{ failure() }}